language: go
go:
  - "1.14"
os:
  - linux
  - osx
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget -O go.tar.gz https://storage.googleapis.com/golang/go1.9.darwin-amd64.tar.gz; else wget -O go.tar.gz https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz; fi
  - tar -C /tmp -xvf go.tar.gz go/bin/gofmt
  - rm go.tar.gz
